Repository spietras/rules_conda, pull requests merged in 2021-11, with the labels that each got.

#27 Moved `tests` to `tests/miniconda`
  .github/workflows/test.yml
  tests/miniconda/.bazeliskrc
  tests/miniconda/BUILD
  tests/miniconda/WORKSPACE
  tests/miniconda/environment.yml
  tests/miniconda/test.py
Labels: cleanup, skip-changelog

#21 Added `miniforge` support
  .github/workflows/test.yml
  README.md
  conda.bzl
  docs/docs/usage/api.md
  docs/docs/usage/example.md
  example/third_party/conda/py3_environment.yml
  tests/miniforge/.bazeliskrc
  tests/miniforge/BUILD
  tests/miniforge/WORKSPACE
  tests/miniforge/environment.yml
  tests/miniforge/test.py
  utils.bzl
Labels: feature

#22 Added `mamba` support
  .github/workflows/test.yml
  conda.bzl
  defs.bzl
  docs/docs/usage/api.md
  docs/docs/usage/example.md
  env.bzl
  example/WORKSPACE
  tests/miniconda/conda/.bazeliskrc
  tests/miniconda/conda/BUILD
  tests/miniconda/conda/WORKSPACE
  tests/miniconda/conda/environment.yml
  tests/miniconda/conda/test.py
  tests/miniconda/mamba/.bazeliskrc
  tests/miniconda/mamba/BUILD
  tests/miniconda/mamba/WORKSPACE
  tests/miniconda/mamba/environment.yml
  tests/miniconda/mamba/test.py
  tests/miniforge/conda/BUILD
  tests/miniforge/conda/WORKSPACE
  tests/miniforge/conda/environment.yml
  tests/miniforge/conda/test.py
  tests/miniforge/mamba/BUILD
  tests/miniforge/mamba/WORKSPACE
  tests/miniforge/mamba/environment.yml
  tests/miniforge/mamba/test.py
Labels: feature

#33 Fixed example using release version instead of local one by default
  example/WORKSPACE
  tests/miniconda/conda/WORKSPACE
  tests/miniconda/mamba/WORKSPACE
  tests/miniforge/conda/WORKSPACE
  tests/miniforge/mamba/WORKSPACE
Labels: bug, skip-changelog
